// Ship the complete table feature in the npm tarball, independently of the hosted registry.
import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { buildIcons } from './build-icons.ts'

const root = fileURLToPath(new URL('../packages/cli/templates/table/', import.meta.url))
async function collect(directory: string): Promise<Record<string, string>> {
  const result: Record<string, string> = {}
  for (const entry of (await readdir(directory, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name))) {
    const file = path.join(directory, entry.name)
    if (entry.isDirectory()) Object.assign(result, await collect(file))
    else if (/\.(btsx|ts|css)$/.test(entry.name)) result[path.relative(root, file).replaceAll(path.sep, '/')] = await readFile(file, 'utf8')
  }
  return result
}
const iconOutput = path.join(root, 'lib/icons/icons.ts')
const icons = await buildIcons(path.join(root, 'lib/icons/svg'), iconOutput)
if (process.argv.includes('--check')) {
  if (await readFile(iconOutput, 'utf8') !== icons) throw new Error('Table icons are stale. Run bun scripts/build-cli-table-assets.ts.')
} else await writeFile(iconOutput, icons)
const files = await collect(root)
const manifest = JSON.parse(await readFile(path.join(root, 'manifest.json'), 'utf8'))
const content = '// Generated by scripts/build-cli-table-assets.ts. Do not edit.\nexport const tableAssets = ' + JSON.stringify({ files, ...manifest }, null, 2) + '\n'
const output = fileURLToPath(new URL('../packages/cli/src/table-assets.ts', import.meta.url))
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== content) throw new Error('CLI table assets are stale. Run bun scripts/build-cli-table-assets.ts.')
} else await writeFile(output, content)
console.log(`Embedded ${Object.keys(files).length} table files`)
