import { readdir, readFile, writeFile } from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import { optimize, type CustomPlugin, type XastElement } from 'svgo'

// Every icon is redrawn on this grid, so stroke widths and padding compare directly
// and <Icon> can use one viewBox for all of them.
const GRID = 24
const iconName = /^[a-z][a-z0-9-]*$/
const shapes = new Set(['path', 'circle', 'ellipse', 'line', 'polygon', 'polyline', 'rect'])
// Root attributes that describe the file rather than how the art is painted.
const documentAttribute = /^(xmlns(:.*)?|viewBox|width|height|x|y|version|baseProfile|preserveAspectRatio|id|class|style|role|focusable|aria-.*|data-.*)$/
// Any painted color, but not none, an existing currentColor or a url(#gradient) reference.
const paintedColor = /^(?!none$|currentColor$|transparent$|inherit$|url\()/i

// Scales the art onto the grid and moves paint attributes off the root <svg>, whose
// attributes are dropped when the body is inlined into <Icon>. The root then gets the
// fill <Icon> renders with, so the other plugins drop fills that only repeat it.
function normalize(name: string): CustomPlugin {
  let normalized = false
  return {
    name: 'normalizeIcon',
    fn: () => ({
      element: {
        enter(node, parent) {
          if (node.name === 'svg' && parent.type === 'root') {
            // multipass runs every plugin again on the already normalized tree.
            if (normalized) return
            normalized = true
            const viewBox = (node.attributes.viewBox ?? '').trim().split(/[\s,]+/).map(Number)
            if (viewBox.length !== 4 || viewBox.some(Number.isNaN)) throw new Error(`${name}.svg needs a viewBox`)
            const [x, y, width, height] = viewBox
            if (width !== height) throw new Error(`${name}.svg has a ${width}×${height} viewBox. Icons must be square.`)
            const paint: Record<string, string> = {}
            for (const [key, value] of Object.entries(node.attributes)) {
              if (!documentAttribute.test(key)) paint[key] = value
              delete node.attributes[key]
            }
            node.attributes.viewBox = `0 0 ${GRID} ${GRID}`
            node.attributes.fill = 'currentColor'
            const scale = GRID / width
            const transform = [scale !== 1 && `scale(${scale})`, (x !== 0 || y !== 0) && `translate(${-x} ${-y})`].filter(Boolean).join(' ')
            if (transform) paint.transform = transform
            if (Object.keys(paint).length) {
              const group: XastElement = { type: 'element', name: 'g', attributes: paint, children: node.children }
              node.children = [group]
            }
            return
          }
          const origin = node.attributes['transform-origin']
          if (origin !== undefined) {
            if (!/^0(px)? 0(px)?$/.test(origin.trim())) throw new Error(`${name}.svg uses transform-origin="${origin}". Bake the transform into the path instead.`)
            delete node.attributes['transform-origin']
          }
          // Leftover from design tools: font-size does nothing on a shape.
          if (shapes.has(node.name)) delete node.attributes['font-size']
        },
      },
    }),
  }
}

/** Optimizes one icon and returns the markup that goes inside <Icon>'s <svg>. */
export function buildIcon(name: string, source: string): string {
  if (!iconName.test(name)) throw new Error(`"${name}" is not a valid icon name. Use lowercase letters, digits and dashes.`)
  const { data } = optimize(source, {
    multipass: true,
    plugins: [
      normalize(name),
      { name: 'preset-default', params: { overrides: { convertColors: { currentColor: paintedColor } } } },
      // Two icons on one page must not share an id.
      { name: 'prefixIds', params: { prefix: name, delim: '-' } },
    ],
  })
  const body = data.match(/^<svg[^>]*>([\s\S]*)<\/svg>$/)
  if (!body || !body[1]) throw new Error(`${name}.svg has nothing to draw`)
  return body[1]
}

/** Icon names, from the .svg files in a directory. */
export async function listIcons(directory: string): Promise<string[]> {
  return (await readdir(directory)).filter((file) => file.endsWith('.svg')).map((file) => file.slice(0, -4)).sort()
}

const quote = (value: string) => `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`

/** Builds the source of packages/icons/src/icons.ts from packages/icons/svg. */
export async function buildIcons(root: string): Promise<string> {
  const directory = path.join(root, 'packages/icons/svg')
  const lines = []
  for (const name of await listIcons(directory)) {
    const body = buildIcon(name, await readFile(path.join(directory, `${name}.svg`), 'utf8'))
    lines.push(`  ${name.includes('-') ? quote(name) : name}: ${quote(body)},`)
  }
  return [
    '// Generated by scripts/build-icons.ts from packages/icons/svg. Do not edit it by hand:',
    '// add or change an .svg file there, then run `bun run icons:build`.',
    '',
    `export const ICON_VIEWBOX = '0 0 ${GRID} ${GRID}'`,
    '',
    'export const icons = {',
    ...lines,
    '}',
    '',
    'export type IconName = keyof typeof icons',
    '',
  ].join('\n')
}

if (import.meta.main) {
  const root = fileURLToPath(new URL('../', import.meta.url))
  const output = path.join(root, 'packages/icons/src/icons.ts')
  const source = await buildIcons(root)
  if (process.argv.includes('--check')) {
    const current = await readFile(output, 'utf8').catch(() => '')
    if (current !== source) {
      console.error('packages/icons/src/icons.ts is out of date. Run `bun run icons:build`.')
      process.exit(1)
    }
    console.log('packages/icons/src/icons.ts is up to date')
  } else {
    await writeFile(output, source)
    console.log(`Built ${source.match(/^ {2}\S/gm)?.length ?? 0} icons → packages/icons/src/icons.ts`)
  }
}
