// Embed setup assets so the published CLI works without a repository checkout.
import { readFile, writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'
import { buildIcons } from './build-icons.ts'

const root = fileURLToPath(new URL('../', import.meta.url))
const sources = {
  builder: 'scripts/build-icons.ts',
  beastIcon: 'packages/icons/src/Icon.btsx',
  beastTypes: 'packages/icons/src/types.ts',
  beastIndex: 'packages/icons/src/index.ts',
  reactIcon: 'packages/cli/templates/Icon.tsx.txt',
  reactTypes: 'packages/cli/templates/react-types.ts.txt',
  search: 'packages/cli/templates/icons/svg/search.svg',
  menu: 'packages/cli/templates/icons/svg/menu.svg',
  close: 'packages/cli/templates/icons/svg/close.svg',
  arrow: 'packages/cli/templates/icons/svg/arrow-right.svg',
}
const assets = Object.fromEntries(await Promise.all(Object.entries(sources).map(async ([key, file]) => [key, await readFile(path.join(root, file), 'utf8')])))
assets.initialIcons = await buildIcons(path.join(root, 'packages/cli/templates/icons/svg'), path.join(root, 'packages/cli/templates/icons/icons.ts'))
const output = path.join(root, 'packages/cli/src/icon-assets.ts')
const content = '// Generated by scripts/build-cli-icon-assets.ts. Do not edit.\nexport const iconAssets = ' + JSON.stringify(assets, null, 2) + '\n'
if (process.argv.includes('--check')) {
  if (await readFile(output, 'utf8') !== content) throw new Error('CLI icon assets are stale. Run bun scripts/build-cli-icon-assets.ts.')
} else {
  await writeFile(output, content)
}
